input LoginInput {
  username: String
  password: String
  deviceId: String
  byPass: Boolean
}

extend type Mutation {
  """
  Login into Equivalen app
  """
  login(auth: LoginInput): LoginResponse!
}
