type UserStudent {
  id: ID!
  nisnNumber: String
  grade: String
}

input UserStudentInput {
  nisnNumber: String!
  grade: String
}

extend type Mutation {
  """
  createUserStudent is deprecated. use createOrUpdateUserStudent!
  """
  createUserStudent(userStudent: UserStudentInput): UserStudent!

  """
  Create or update Authenticated user student data.
  """
  createOrUpdateUserStudent(userStudent: UserStudentInput): UserStudent!
}
