type UserRelationship {
  id: ID!
  user: User
  userTarget: User
  status: String
}

input UserRelationInput {
  id: ID
}

extend type Mutation {
  addTeacherRelationship(userTarget: UserRelationInput): UserRelationship
  approveRequestRelationship(userTarget: UserRelationInput): UserRelationship
}
