type UserStudent {
  id: ID!
  nisnNumber: String
}

input UserStudentInput {
  nisnNumber: String!
}

extend type Mutation {
  createUserStudent(
    userStudent: UserStudentInput @deprecated(reason: "use createOrUpdateUserStudent")
  ): UserStudent!
  createOrUpdateUserStudent(
    userStudent: UserStudentInput
  ): UserStudent!
}