type UserSchool {
  id: ID!
  user: User!
  school: School!
  startYear: Int
  endYear: Int
}

input UserSchoolInput {
  startYear: String
  endYear: String
  school: SchoolInput!
}

extend type Mutation {
  createUserSchool (
    userSchool: UserSchoolInput
  ): UserSchool!
}