type UserTeacher {
  id: ID!
  nuptkNumber: String
  courses: [Course]
}

input UserTeacherInput {
  nuptkNumber: String!
  courses: [CourseInput]
}

extend type Mutation {
  """
  Create or update Authenticated user Teacher data.
  """
  createOrUpdateUserTeacher(userTeacher: UserTeacherInput): UserTeacher!
}
