type UserProfile {
  id: ID!
  nikNumber: String
}

input UserProfileInput {
  nikNumber: String
}

extend type Mutation {
  """
  createUserProfile is deprecated. use createOrUpdateUserProfile!
  """
  createUserProfile(userProfile: UserProfileInput): UserProfile

  """
  Create or update authenticated user profile data.
  """
  createOrUpdateUserProfile(userProfile: UserProfileInput): UserProfile
}
