type UserProfile {
  id: ID!
  nikNumber: String
}

input UserProfileInput {
  nikNumber: String!
}

extend type Mutation {
  createUserProfile(
    userProfile: UserProfileInput @deprecated(reason: "use createOrUpdateUserProfile")
  ): UserProfile!

  createOrUpdateUserProfile(
    userProfile: UserProfileInput
  ): UserProfile!
}