type UserPrefillResponse {
  phoneNumber: String
}

type PrefillResponse {
  user: UserPrefillResponse
  token: String
}

input RegisterUserInput {
  email: String @constraint(format: "email")
  fullName: String!
  username: String!
  gender: String
  phoneNumber: String!
  password: String!
  placeBod: String
  dateBod: Date
  biography: String
}
