type City {
  id: ID!
  name: String
  province: Province
  districts: [District!]
  schools: [School!]
}

input CityInput {
  id: ID
  name: String
  province: ProvinceInput
}

extend type Query {
  """
  Get list of cities.
  """
  cities(provinceId: ID): [City]
}