type Classes {
  id: ID
  name: String
  grade: Grade
}

input ClassesInput {
  id: ID
  name: String
  grade: GradeInput
}

extend type Query {
  """
  Get list of classes.
  """
  classes(grade: GradeInput): [Classes]
}