type School {
  id: ID!
  name: String!
  province: Province
  city: City
  district: District
  users: [User!]
}

input SchoolInput {
  name: String!
  province: ProvinceInput
  city: CityInput
  district: DistrictInput
}

extend type Query {
  """
  Get list of schools.
  """
  schools(keyword: String): [School!]
}
