type Chapter {
  id: ID
  name: String
  course: Course
}

input ChapterInput {
  id: ID
  name: String
}

extend type Query {
  chapters(
    courseId: ID
    limit: Int
    offset: Int
  ): [Chapter]
}