type QuestionOption {
  id: ID!
  content: String!
  order: Int!
  option: Option!
  createdAt: Date!
  updatedAt: Date!
}

type QuestionInfo {
  id: ID
  curriculum: Curriculum
  course: Course
  chapter: Chapter
  question: Question
}

type Question {
  id: ID!
  content: String!
  type: QuestionType!
  used: Int
  answer: String
  questionInfos: [QuestionInfo]
  options: [QuestionOption!]
  createdBy: User
  createdAt: Date!
  updatedAt: Date!
}

input QuestionOptionInput {
  content: String
  order: Int!
  option: OptionInput!
}

input QuestionInput {
  content: String!
  answer: String
  type: QuestionTypeInput!
  options: [QuestionOptionInput]
}

extend type Query {
  questions: [Question!]
}

extend type Mutation {
  """
  Create Question Option
  """
  createOrUpdateQuestion(question: QuestionInput): Question
}