type QuestionType {
  id: ID!
  name: String!
}

input QuestionTypeInput {
  id: ID
  name: String
}

extend type Query {
  questionTypes: [QuestionType]
}

extend type Mutation {
  findQuestionType(questionType: QuestionTypeInput): QuestionType
  createOrUpdateQuestionType(questionType: QuestionTypeInput): QuestionType
}