type UserPrefillResponse {
  phoneNumber: String
}

type PrefillResponse {
  user: UserPrefillResponse
  token: String
}

type RegisterResponse {
  user: User!
  token: String!
}

input RegisterUserInput {
  email: String!
  username: String!
  phoneNumber: String!
  password: String!
}